// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq1DKOKZlQJwVBLmLckLaijc5OcAX9ea0',
    appId: '1:305163912569:web:bb0c588868773d0dfb1ba8',
    messagingSenderId: '305163912569',
    projectId: 'weather-app-e5714',
    authDomain: 'weather-app-e5714.firebaseapp.com',
    storageBucket: 'weather-app-e5714.appspot.com',
    measurementId: 'G-4KB4ZR3GL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGeat6I-4Xjd33wbtQ7qgl81OS-epCpmM',
    appId: '1:305163912569:android:98cba02fb995a0c4fb1ba8',
    messagingSenderId: '305163912569',
    projectId: 'weather-app-e5714',
    storageBucket: 'weather-app-e5714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgeXTzS4TTzqu7cRUpKZBtu67AvkzDVmM',
    appId: '1:305163912569:ios:7cf86c90620fca92fb1ba8',
    messagingSenderId: '305163912569',
    projectId: 'weather-app-e5714',
    storageBucket: 'weather-app-e5714.appspot.com',
    iosClientId: '305163912569-jeh4nko481ko4sf1odqa5uuletju27r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
